# Generated by Django 4.2.2 on 2023-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='DiscountPrice',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
