# Generated by Django 4.2.2 on 2023-09-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Product', '0002_alter_products_discountprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField()),
                ('data', models.DateTimeField(auto_now=True)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profiles')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.products')),
            ],
        ),
    ]
