# Generated by Django 4.2.2 on 2023-09-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='Profile',
        ),
        migrations.AddField(
            model_name='reviews',
            name='Email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='Name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
