# Generated by Django 4.2.2 on 2023-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_products_discountprice_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
        migrations.AddField(
            model_name='reviews',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Rating',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
