# Generated by Django 4.2.2 on 2023-09-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
