# Generated by Django 4.2.2 on 2023-09-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_orderdetails_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='total',
        ),
    ]
