# Generated by Django 4.2.2 on 2023-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_orderdetails_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
