# Generated by Django 4.2.5 on 2023-09-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_orderdetails_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='size',
        ),
    ]
